package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * Authority generated by hbm2java
 */
public class Authority implements java.io.Serializable {

	private String authoid;
	private String authoType;
	private String authoUrl;

	public Authority() {
	}

	public Authority(String authoid, String authoType, String authoUrl) {
		this.authoid = authoid;
		this.authoType = authoType;
		this.authoUrl = authoUrl;
	}

	public String getAuthoid() {
		return this.authoid;
	}

	public void setAuthoid(String authoid) {
		this.authoid = authoid;
	}

	public String getAuthoType() {
		return this.authoType;
	}

	public void setAuthoType(String authoType) {
		this.authoType = authoType;
	}

	public String getAuthoUrl() {
		return this.authoUrl;
	}

	public void setAuthoUrl(String authoUrl) {
		this.authoUrl = authoUrl;
	}

}
