package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Short menuid;
	private String foodName;
	private short price;
	private String restaurantid;

	public Menu() {
	}

	public Menu(String foodName, short price) {
		this.foodName = foodName;
		this.price = price;
	}

	public Menu(String foodName, short price, String restaurantid) {
		this.foodName = foodName;
		this.price = price;
		this.restaurantid = restaurantid;
	}

	public Short getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Short menuid) {
		this.menuid = menuid;
	}

	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public short getPrice() {
		return this.price;
	}

	public void setPrice(short price) {
		this.price = price;
	}

	public String getRestaurantid() {
		return this.restaurantid;
	}

	public void setRestaurantid(String restaurantid) {
		this.restaurantid = restaurantid;
	}

}
