package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private String restaurantid;
	private String name;
	private String boss;
	private String address;
	private String info;
	private String photoUrl;

	public Restaurant() {
	}

	public Restaurant(String restaurantid, String name, String boss) {
		this.restaurantid = restaurantid;
		this.name = name;
		this.boss = boss;
	}

	public Restaurant(String restaurantid, String name, String boss,
			String address, String info, String photoUrl) {
		this.restaurantid = restaurantid;
		this.name = name;
		this.boss = boss;
		this.address = address;
		this.info = info;
		this.photoUrl = photoUrl;
	}

	public String getRestaurantid() {
		return this.restaurantid;
	}

	public void setRestaurantid(String restaurantid) {
		this.restaurantid = restaurantid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBoss() {
		return this.boss;
	}

	public void setBoss(String boss) {
		this.boss = boss;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

}
