package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * RoleAuthority generated by hbm2java
 */
public class RoleAuthority implements java.io.Serializable {

	private String id;
	private String roleid;
	private String authoid;

	public RoleAuthority() {
	}

	public RoleAuthority(String id, String roleid, String authoid) {
		this.id = id;
		this.roleid = roleid;
		this.authoid = authoid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getAuthoid() {
		return this.authoid;
	}

	public void setAuthoid(String authoid) {
		this.authoid = authoid;
	}

}
