package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Sysorder generated by hbm2java
 */
public class Sysorder implements java.io.Serializable {

	private String orderid;
	private Date orderTime;
	private String custid;
	private String restaurantid;
	private Short money;
	private String statues;

	public Sysorder() {
	}

	public Sysorder(String orderid, Date orderTime, String custid,
			String restaurantid) {
		this.orderid = orderid;
		this.orderTime = orderTime;
		this.custid = custid;
		this.restaurantid = restaurantid;
	}

	public Sysorder(String orderid, Date orderTime, String custid,
			String restaurantid, Short money, String statues) {
		this.orderid = orderid;
		this.orderTime = orderTime;
		this.custid = custid;
		this.restaurantid = restaurantid;
		this.money = money;
		this.statues = statues;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getCustid() {
		return this.custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	public String getRestaurantid() {
		return this.restaurantid;
	}

	public void setRestaurantid(String restaurantid) {
		this.restaurantid = restaurantid;
	}

	public Short getMoney() {
		return this.money;
	}

	public void setMoney(Short money) {
		this.money = money;
	}

	public String getStatues() {
		return this.statues;
	}

	public void setStatues(String statues) {
		this.statues = statues;
	}

}
