package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private Integer taskid;
	private String orderid;
	private String delever;
	private String statues;

	public Task() {
	}

	public Task(String orderid, String delever) {
		this.orderid = orderid;
		this.delever = delever;
	}

	public Task(String orderid, String delever, String statues) {
		this.orderid = orderid;
		this.delever = delever;
		this.statues = statues;
	}

	public Integer getTaskid() {
		return this.taskid;
	}

	public void setTaskid(Integer taskid) {
		this.taskid = taskid;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getDelever() {
		return this.delever;
	}

	public void setDelever(String delever) {
		this.delever = delever;
	}

	public String getStatues() {
		return this.statues;
	}

	public void setStatues(String statues) {
		this.statues = statues;
	}

}
