package org.sophia.eorder.domain;
// Generated 2013-7-4 0:35:54 by Hibernate Tools 3.4.0.CR1

/**
 * UsserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private String userid;
	private String mobileNum;
	private String address;
	private String photoUrl;

	public UserInfo() {
	}

	public UserInfo(String userid, String mobileNum, String address) {
		this.userid = userid;
		this.mobileNum = mobileNum;
		this.address = address;
	}

	public UserInfo(String userid, String mobileNum, String address,
			String photoUrl) {
		this.userid = userid;
		this.mobileNum = mobileNum;
		this.address = address;
		this.photoUrl = photoUrl;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getMobileNum() {
		return this.mobileNum;
	}

	public void setMobileNum(String mobileNum) {
		this.mobileNum = mobileNum;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder("[User Info:\n");
		builder.append("Mobile Number:").append(mobileNum).append("\n")
		.append("address:").append(address).append("]");
		return builder.toString();
	}
}
